#!/usr/bin/env python3

import fatstack as fs
import fatstack.cli
import fatstack.logging
import logging

fatstack.logging.init_bootstrap()
log = logging.getLogger(__file__)

log.info("Starting FATStack %s.", fs.__version__)
fatstack.cli.parse_args()

fatstack.logging.init_final()
log.info("Test")

# Initializing the event loop
fs.loop.init()

if fs.ROOT.Config.collector:
    import fatstack.collector
    fatstack.collector.init(fs.ROOT.Config.collector)

if not fs.ROOT.Config.no_shell:
    import fatstack.shell
    fs.ROOT.Sys.shell = fatstack.shell.Shell(fs.ROOT.__dict__)

fs.loop.finish_all()
